<?php
// Turn off warnings and notices to prevent any output before PDF generation
error_reporting(E_ERROR | E_PARSE);

require_once '../database.php';

// Try to include Composer autoloader if available
if (file_exists('../vendor/autoload.php')) {
    require '../vendor/autoload.php';
}

// Check if session already started to avoid warning
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Check authentication
if (!isset($_SESSION['username']) || $_SESSION['user_type'] !== 'Admin') {
    header("Location: ../unauthorized.php");
    exit;
}

// Get export format and date range
$format = isset($_GET['format']) ? strtolower($_GET['format']) : 'excel';
$startDate = isset($_GET['start']) ? $_GET['start'] : date('Y-m-d', strtotime('-30 days'));
$endDate = isset($_GET['end']) ? $_GET['end'] : date('Y-m-d');
$empId = isset($_GET['emp_id']) ? $_GET['emp_id'] : null;
$action = isset($_GET['action']) ? $_GET['action'] : null;

// Get password from request or use default
$encryptionPassword = $_GET['encryption_password'] ?? "paradisehotel2025";

// Store who generated the report
$generatedBy = $_SESSION['username'] ?? 'Unknown User';

// Validate dates
if (!strtotime($startDate) || !strtotime($endDate)) {
    echo "Invalid date range";
    exit;
}

// Add one day to end date for inclusive filtering
$endDateForQuery = date('Y-m-d', strtotime($endDate . ' +1 day'));

// Build the query with any filters
$conditions = [];
$params = [];
$types = "";

// Add date range condition
$conditions[] = "tl.log_time BETWEEN ? AND ?";
$params[] = $startDate;
$params[] = $endDateForQuery;
$types .= "ss";

// Add employee filter if provided
if ($empId) {
    $conditions[] = "tl.emp_id = ?";
    $params[] = $empId;
    $types .= "s";
}

// Add action filter if provided
if ($action) {
    $conditions[] = "tl.action = ?";
    $params[] = $action;
    $types .= "s";
}

// Construct WHERE clause
$whereClause = !empty($conditions) ? " WHERE " . implode(" AND ", $conditions) : "";

// Join with employee table to get employee names
$logsQuery = "SELECT tl.log_id, tl.task_id, tl.emp_id, e.name as employee_name, 
              tl.action, tl.change_details, tl.log_time 
              FROM task_logs tl
              LEFT JOIN employee e ON tl.emp_id = e.emp_id" . 
              $whereClause . 
              " ORDER BY tl.log_time DESC";

$stmt = $conn->prepare($logsQuery);
if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$result = $stmt->get_result();

$data = [];
if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $data[] = $row;
    }
}

// Generate filename with date range
$filename = "task_logs_{$startDate}_to_{$endDate}";

// Export based on format
if ($format === 'excel') {
    exportToExcel($data, $filename, $startDate, $endDate, $generatedBy, $action, $encryptionPassword);
} elseif ($format === 'pdf') {
    exportToPDF($data, $filename, $startDate, $endDate, $generatedBy, $action, $encryptionPassword);
} else {
    echo "Invalid export format";
    exit;
}

/**
 * Export logs data to Excel
 */
function exportToExcel($data, $filename, $startDate, $endDate, $generatedBy, $action, $encryptionPassword) {
    // Create temporary file for the Excel output
    $tempFile = tempnam(sys_get_temp_dir(), 'excel');
    
    // Generate the Excel content and save to the temp file
    $fh = fopen($tempFile, 'w');
    
    // Start output
    $excelContent = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel">';
    $excelContent .= '<head>';
    $excelContent .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
    $excelContent .= '<style>';
    $excelContent .= 'table { border-collapse: collapse; }';
    $excelContent .= 'th, td { border: 1px solid #000000; padding: 5px; }';
    $excelContent .= 'th { background-color: #f0f0f0; font-weight: bold; }';
    $excelContent .= '.summary-row { background-color: #f0f0f0; font-weight: bold; }';
    $excelContent .= '.assigned { color: #0275d8; }'; // Blue
    $excelContent .= '.updated { color: #f0ad4e; }';  // Orange
    $excelContent .= '.completed { color: #5cb85c; }'; // Green
    $excelContent .= '.canceled { color: #d9534f; }';  // Red
    $excelContent .= '.report-header { font-size: 14pt; font-weight: bold; margin-bottom: 10px; }';
    $excelContent .= '.report-meta { font-size: 10pt; margin-bottom: 20px; }';
    $excelContent .= '</style>';
    $excelContent .= '</head>';
    $excelContent .= '<body>';
    
    // Report title and metadata
    $excelContent .= '<div class="report-header">Task Logs Report</div>';
    $excelContent .= '<div class="report-meta">';
    $excelContent .= 'Generated on: ' . date('Y-m-d H:i:s') . '<br>';
    $excelContent .= 'Generated by: ' . $generatedBy . '<br>';
    $excelContent .= 'Period: ' . $startDate . ' to ' . $endDate . '<br>';
    if ($action) {
        $excelContent .= 'Action Filter: ' . ucfirst($action) . '<br>';
    }
    $excelContent .= '</div>';
    
    // Table start
    $excelContent .= '<table border="1">';
    
    // Header row
    $excelContent .= '<tr>';
    $excelContent .= '<th>Log ID</th>';
    $excelContent .= '<th>Task ID</th>';
    $excelContent .= '<th>Employee ID</th>';
    $excelContent .= '<th>Employee Name</th>';
    $excelContent .= '<th>Action</th>';
    $excelContent .= '<th>Details</th>';
    $excelContent .= '<th>Date & Time</th>';
    $excelContent .= '</tr>';
    
    // Data rows
    if (count($data) > 0) {
        foreach ($data as $row) {
            $logTime = date('Y-m-d H:i', strtotime($row['log_time']));
            
            // Get values with fallbacks for missing data
            $employeeName = isset($row['employee_name']) && !empty($row['employee_name']) 
                          ? $row['employee_name'] 
                          : 'Unknown';
            
            // Get CSS class based on action
            $actionClass = strtolower($row['action']);
            
            $excelContent .= '<tr>';
            $excelContent .= '<td>' . $row['log_id'] . '</td>';
            $excelContent .= '<td>' . (isset($row['task_id']) && $row['task_id'] ? $row['task_id'] : 'N/A') . '</td>';
            $excelContent .= '<td>' . $row['emp_id'] . '</td>';
            $excelContent .= '<td>' . $employeeName . '</td>';
            $excelContent .= '<td class="' . $actionClass . '">' . ucfirst($row['action']) . '</td>';
            $excelContent .= '<td>' . (isset($row['change_details']) && $row['change_details'] ? $row['change_details'] : '') . '</td>';
            $excelContent .= '<td>' . $logTime . '</td>';
            $excelContent .= '</tr>';
        }
        
        // Add summary row
        $excelContent .= '<tr><td colspan="7"></td></tr>';
        $excelContent .= '<tr class="summary-row">';
        $excelContent .= '<td colspan="3">Total Records:</td>';
        $excelContent .= '<td colspan="4">' . count($data) . '</td>';
        $excelContent .= '</tr>';
        
        // Count tasks by action type
        $actionCounts = [];
        foreach ($data as $row) {
            $action = strtolower($row['action']);
            if (isset($actionCounts[$action])) {
                $actionCounts[$action]++;
            } else {
                $actionCounts[$action] = 1;
            }
        }
        
        // Show action type summary
        foreach ($actionCounts as $action => $count) {
            $excelContent .= '<tr class="summary-row">';
            $excelContent .= '<td colspan="3">Total ' . ucfirst($action) . ':</td>';
            $excelContent .= '<td colspan="4">' . $count . '</td>';
        }
        
        $excelContent .= '<tr class="summary-row">';
        $excelContent .= '<td colspan="3">Period:</td>';
        $excelContent .= '<td colspan="4">' . $startDate . ' to ' . $endDate . '</td>';
        $excelContent .= '</tr>';
    } else {
        $excelContent .= '<tr><td colspan="7">No task logs found for the selected period</td></tr>';
    }
    
    $excelContent .= '</table>';
    $excelContent .= '</body></html>';
    
    // Write the content to the temp file
    fwrite($fh, $excelContent);
    fclose($fh);
    
    // Create a zip archive to password protect the Excel file
    $zipFile = tempnam(sys_get_temp_dir(), 'zip');
    $zip = new ZipArchive();
    
    if ($zip->open($zipFile, ZipArchive::CREATE | ZipArchive::OVERWRITE) === TRUE) {
        // Set password for the Excel file
        $zip->setPassword($encryptionPassword);
        
        // Add the Excel file to the zip archive with encryption
        $zip->addFile($tempFile, $filename . '.xls');
        $zip->setEncryptionName($filename . '.xls', ZipArchive::EM_AES_256);
        $zip->close();
        
        // Set headers for download
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $filename . '_protected.zip"');
        header('Content-Length: ' . filesize($zipFile));
        header('Pragma: no-cache');
        header('Expires: 0');
        
        // Output the zip file
        readfile($zipFile);
        
        // Clean up temp files
        @unlink($tempFile);
        @unlink($zipFile);
        exit;
    } else {
        // Fallback to unprotected Excel if zip creation fails
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment; filename="' . $filename . '.xls"');
        header('Pragma: no-cache');
        header('Expires: 0');
        readfile($tempFile);
        @unlink($tempFile);
        exit;
    }
}

/**
 * Export logs data to PDF using FPDF or TCPDF with password protection
 */
function exportToPDF($data, $filename, $startDate, $endDate, $generatedBy, $action, $encryptionPassword) {
    try {
        // Clear all previous output and buffers
        while (ob_get_level()) {
            ob_end_clean();
        }
        
        // Check if TCPDF is available (preferred for security features)
        if (class_exists('TCPDF')) {
            // Create new PDF document with TCPDF
            $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
            
            // Set document information
            $pdf->SetCreator('Paradise Hotel');
            $pdf->SetAuthor($generatedBy);
            $pdf->SetTitle('Task Logs Report');
            $pdf->SetSubject('Export Report');
            
            // Set PDF protection
            $pdf->SetProtection(array('print', 'copy'), $encryptionPassword, null, 0, null);
            
            // Remove default header/footer
            $pdf->setPrintHeader(false);
            $pdf->setPrintFooter(false);
            
            // Set margins
            $pdf->SetMargins(15, 15, 15);
            
            // Set auto page breaks
            $pdf->SetAutoPageBreak(TRUE, 15);
            
            // Add a page
            $pdf->AddPage();
            
            // Add title
            $pdf->SetFont('helvetica', 'B', 16);
            $pdf->Cell(0, 10, 'Task Logs Report', 0, 1, 'C');
            $pdf->SetFont('helvetica', '', 10);
            $pdf->Cell(0, 6, 'Period: ' . $startDate . ' to ' . $endDate, 0, 1, 'C');
            $pdf->Cell(0, 6, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 1, 'C');
            $pdf->Cell(0, 6, 'Generated by: ' . $generatedBy, 0, 1, 'C');
            
            if ($action) {
                $pdf->Cell(0, 6, 'Action Filter: ' . ucfirst($action), 0, 1, 'C');
            }
            
            $pdf->Ln(5);
            
            // Define table column widths
            $pageWidth = $pdf->getPageWidth() - 30; // Adjust for margins
            $columnWidths = [
                10,  // Log ID
                15,  // Task ID
                18,  // Employee ID
                40,  // Employee Name
                25,  // Action
                45,  // Details
                30   // Date & Time
            ];
            
            // Adjust column widths to fit page width
            $totalWidth = array_sum($columnWidths);
            if ($totalWidth > $pageWidth) {
                $ratio = $pageWidth / $totalWidth;
                for ($i = 0; $i < count($columnWidths); $i++) {
                    $columnWidths[$i] = $columnWidths[$i] * $ratio;
                }
            }
            
            // Table header
            $pdf->SetFont('helvetica', 'B', 10);
            $pdf->SetFillColor(240, 240, 240);
            $pdf->Cell($columnWidths[0], 8, 'Log ID', 1, 0, 'C', true);
            $pdf->Cell($columnWidths[1], 8, 'Task ID', 1, 0, 'C', true);
            $pdf->Cell($columnWidths[2], 8, 'Emp ID', 1, 0, 'C', true);
            $pdf->Cell($columnWidths[3], 8, 'Employee Name', 1, 0, 'C', true);
            $pdf->Cell($columnWidths[4], 8, 'Action', 1, 0, 'C', true);
            $pdf->Cell($columnWidths[5], 8, 'Details', 1, 0, 'C', true);
            $pdf->Cell($columnWidths[6], 8, 'Date & Time', 1, 1, 'C', true);
            
            // Table data
            $pdf->SetFont('helvetica', '', 9);
            
            // Count actions for summary
            $actionCounts = [];
            
            if (count($data) > 0) {
                foreach ($data as $row) {
                    // Count by action type
                    $actionLower = strtolower($row['action']);
                    if (isset($actionCounts[$actionLower])) {
                        $actionCounts[$actionLower]++;
                    } else {
                        $actionCounts[$actionLower] = 1;
                    }
                    
                    $logTime = date('Y-m-d H:i', strtotime($row['log_time']));
                    
                    // Get values with fallbacks for missing data
                    $employeeName = isset($row['employee_name']) && !empty($row['employee_name']) 
                                  ? $row['employee_name'] 
                                  : 'Unknown';
                    $empId = $row['emp_id'];
                    $logId = $row['log_id'];
                    $taskId = isset($row['task_id']) && $row['task_id'] ? $row['task_id'] : 'N/A';
                    $actionText = ucfirst($row['action']);
                    $details = isset($row['change_details']) ? $row['change_details'] : '';
                    
                    // Truncate long fields
                    if (strlen($details) > 35) {
                        $details = substr($details, 0, 32) . '...';
                    }
                    if (strlen($employeeName) > 25) {
                        $employeeName = substr($employeeName, 0, 22) . '...';
                    }
                    
                    // Set text color based on action
                    if (strtolower($actionText) === 'assigned') {
                        $pdf->SetTextColor(2, 117, 216); // Blue
                    } elseif (strtolower($actionText) === 'updated') {
                        $pdf->SetTextColor(240, 173, 78); // Orange
                    } elseif (strtolower($actionText) === 'completed') {
                        $pdf->SetTextColor(92, 184, 92); // Green
                    } elseif (strtolower($actionText) === 'canceled') {
                        $pdf->SetTextColor(217, 83, 79); // Red
                    } else {
                        $pdf->SetTextColor(0, 0, 0); // Black
                    }
                    
                    // Print row
                    $pdf->Cell($columnWidths[0], 7, $logId, 1, 0, 'C');
                    $pdf->Cell($columnWidths[1], 7, $taskId, 1, 0, 'C');
                    
                    $pdf->SetTextColor(0, 0, 0); // Reset to black for remaining fields
                    $pdf->Cell($columnWidths[2], 7, $empId, 1, 0, 'C');
                    $pdf->Cell($columnWidths[3], 7, $employeeName, 1, 0, 'L');
                    
                    // Set action color again for the action column
                    if (strtolower($actionText) === 'assigned') {
                        $pdf->SetTextColor(2, 117, 216); // Blue
                    } elseif (strtolower($actionText) === 'updated') {
                        $pdf->SetTextColor(240, 173, 78); // Orange
                    } elseif (strtolower($actionText) === 'completed') {
                        $pdf->SetTextColor(92, 184, 92); // Green
                    } elseif (strtolower($actionText) === 'canceled') {
                        $pdf->SetTextColor(217, 83, 79); // Red
                    } else {
                        $pdf->SetTextColor(0, 0, 0); // Black
                    }
                    
                    $pdf->Cell($columnWidths[4], 7, $actionText, 1, 0, 'C');
                    
                    $pdf->SetTextColor(0, 0, 0); // Reset to black
                    $pdf->Cell($columnWidths[5], 7, $details, 1, 0, 'L');
                    $pdf->Cell($columnWidths[6], 7, $logTime, 1, 1, 'C');
                    
                    // Check if we need a new page
                    if ($pdf->GetY() > 265) {
                        $pdf->AddPage();
                        
                        // Repeat header on the new page
                        $pdf->SetFont('helvetica', 'B', 10);
                        $pdf->SetFillColor(240, 240, 240);
                        $pdf->Cell($columnWidths[0], 8, 'Log ID', 1, 0, 'C', true);
                        $pdf->Cell($columnWidths[1], 8, 'Task ID', 1, 0, 'C', true);
                        $pdf->Cell($columnWidths[2], 8, 'Emp ID', 1, 0, 'C', true);
                        $pdf->Cell($columnWidths[3], 8, 'Employee Name', 1, 0, 'C', true);
                        $pdf->Cell($columnWidths[4], 8, 'Action', 1, 0, 'C', true);
                        $pdf->Cell($columnWidths[5], 8, 'Details', 1, 0, 'C', true);
                        $pdf->Cell($columnWidths[6], 8, 'Date & Time', 1, 1, 'C', true);
                        $pdf->SetFont('helvetica', '', 9);
                    }
                }
                
                // Summary section
                $pdf->Ln(10);
                $pdf->SetFont('helvetica', 'B', 12);
                $pdf->Cell(0, 8, 'Logs Summary', 0, 1, 'L');
                $pdf->SetFont('helvetica', '', 10);
                $pdf->SetTextColor(0, 0, 0); // Reset to black
                
                $pdf->Cell(80, 7, 'Total Records:', 0, 0, 'L');
                $pdf->Cell(0, 7, count($data), 0, 1, 'L');
                
                // Show action type summary
                foreach ($actionCounts as $action => $count) {
                    // Set color based on action type
                    if ($action === 'assigned') {
                        $pdf->SetTextColor(2, 117, 216); // Blue
                    } elseif ($action === 'updated') {
                        $pdf->SetTextColor(240, 173, 78); // Orange
                    } elseif ($action === 'completed') {
                        $pdf->SetTextColor(92, 184, 92); // Green
                    } elseif ($action === 'canceled') {
                        $pdf->SetTextColor(217, 83, 79); // Red
                    } else {
                        $pdf->SetTextColor(0, 0, 0); // Black
                    }
                    
                    $pdf->Cell(80, 7, 'Total ' . ucfirst($action) . ':', 0, 0, 'L');
                    $pdf->Cell(0, 7, $count, 0, 1, 'L');
                    
                    // Reset color to black
                    $pdf->SetTextColor(0, 0, 0);
                }
                
                $pdf->Cell(80, 7, 'Period:', 0, 0, 'L');
                $pdf->Cell(0, 7, $startDate . ' to ' . $endDate, 0, 1, 'L');
            } else {
                $pdf->Cell(0, 10, 'No task logs found for the selected period', 1, 1, 'C');
            }
            
            // Output PDF
            $pdf->Output($filename . '.pdf', 'D');
            exit;
        } 
        // Fall back to FPDF if TCPDF is not available
        else if (class_exists('FPDF')) {
            // Use FPDF - changed to portrait orientation
            $pdf = new FPDF('P', 'mm', 'A4');
            $pdf->AddPage();
            
            // Add title
            $pdf->SetFont('Arial', 'B', 16);
            $pdf->Cell(0, 10, 'Task Logs Report', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 10);
            $pdf->Cell(0, 6, 'Period: ' . $startDate . ' to ' . $endDate, 0, 1, 'C');
            $pdf->Cell(0, 6, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 1, 'C');
            $pdf->Cell(0, 6, 'Generated by: ' . $generatedBy, 0, 1, 'C');
            
            if ($action) {
                $pdf->Cell(0, 6, 'Action Filter: ' . ucfirst($action), 0, 1, 'C');
            }
            
            $pdf->Ln(5);
            
            // Column widths
            $colWidth = [10, 15, 15, 40, 20, 50, 30];
            
            // Table header
            $pdf->SetFont('Arial', 'B', 8);
            $pdf->SetFillColor(240, 240, 240);
            $pdf->Cell($colWidth[0], 8, 'Log ID', 1, 0, 'C', true);
            $pdf->Cell($colWidth[1], 8, 'Task ID', 1, 0, 'C', true);
            $pdf->Cell($colWidth[2], 8, 'Emp ID', 1, 0, 'C', true);
            $pdf->Cell($colWidth[3], 8, 'Employee Name', 1, 0, 'C', true);
            $pdf->Cell($colWidth[4], 8, 'Action', 1, 0, 'C', true);
            $pdf->Cell($colWidth[5], 8, 'Details', 1, 0, 'C', true);
            $pdf->Cell($colWidth[6], 8, 'Date & Time', 1, 1, 'C', true);
            
            // Similar implementation to TCPDF section but without password protection
            // ...as FPDF doesn't support it natively
            
            // Output PDF
            $pdf->Output('D', $filename . '.pdf');
            exit;
        } else {
            // Fallback to simple HTML output if no PDF libraries are available
            header('Content-Type: text/html; charset=utf-8');
            echo "<h1>Task Logs Report</h1>";
            echo "<p>Period: {$startDate} to {$endDate}</p>";
            echo "<p>PDF generation requires a PDF library like FPDF or TCPDF.</p>";
            echo "<p>Please try exporting to Excel format instead or install a PDF library.</p>";
            echo "<p><a href='../task_allocation.php'>Return to Task Allocation</a></p>";
            exit;
        }
    } catch (Exception $e) {
        // Error handling
        header('Content-Type: text/html; charset=utf-8');
        echo "<h1>PDF Export Error</h1>";
        echo "<p>An error occurred while generating the PDF: " . $e->getMessage() . "</p>";
        echo "<p>Please try exporting to Excel format instead.</p>";
        echo "<p><a href='../task_allocation.php'>Return to Task Allocation</a></p>";
        exit;
    }
}
?>
